# Project: 2.5D Game
# Makefile created by Dev-C++ 5.7.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Material.o World.o Building.o Drawing.o Main.o Texture.o Item.o Bot.o Player.o Input.o Camera.o Lighting.o Menu.o Cutscene.o Sound.o Jumpscare.o Shadow.o
LINKOBJ  = Material.o World.o Building.o Drawing.o Main.o Texture.o Item.o Bot.o Player.o Input.o Camera.o Lighting.o Menu.o Cutscene.o Sound.o Jumpscare.o Shadow.o
LIBS     = -L"C:/Program Files (x86)/GibsTeam/Dev-C++ GTI MOD/Dev-Cpp/Dev-Cpp/MinGW32/lib" -static-libstdc++ -static-libgcc -mwindows -lglut32 -lglu32 -lopengl32 -lwinmm -lgdi32
INCS     = -I"C:/Program Files (x86)/GibsTeam/Dev-C++ GTI MOD/Dev-Cpp/Dev-Cpp/MinGW32/include"
CXXINCS  = -I"C:/Program Files (x86)/GibsTeam/Dev-C++ GTI MOD/Dev-Cpp/Dev-Cpp/MinGW32/include"
BIN      = "2.5D Game.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) -DGLUT_STATIC
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Material.o: Material.cpp
	$(CPP) -c Material.cpp -o Material.o $(CXXFLAGS)

World.o: World.cpp
	$(CPP) -c World.cpp -o World.o $(CXXFLAGS)

Building.o: Building.cpp
	$(CPP) -c Building.cpp -o Building.o $(CXXFLAGS)

Drawing.o: Drawing.cpp
	$(CPP) -c Drawing.cpp -o Drawing.o $(CXXFLAGS)

Main.o: Main.cpp
	$(CPP) -c Main.cpp -o Main.o $(CXXFLAGS)

Texture.o: Texture.cpp
	$(CPP) -c Texture.cpp -o Texture.o $(CXXFLAGS)

Item.o: Item.cpp
	$(CPP) -c Item.cpp -o Item.o $(CXXFLAGS)

Bot.o: Bot.cpp
	$(CPP) -c Bot.cpp -o Bot.o $(CXXFLAGS)

Player.o: Player.cpp
	$(CPP) -c Player.cpp -o Player.o $(CXXFLAGS)

Input.o: Input.cpp
	$(CPP) -c Input.cpp -o Input.o $(CXXFLAGS)

Camera.o: Camera.cpp
	$(CPP) -c Camera.cpp -o Camera.o $(CXXFLAGS)

Lighting.o: Lighting.cpp
	$(CPP) -c Lighting.cpp -o Lighting.o $(CXXFLAGS)

Menu.o: Menu.cpp
	$(CPP) -c Menu.cpp -o Menu.o $(CXXFLAGS)

Cutscene.o: Cutscene.cpp
	$(CPP) -c Cutscene.cpp -o Cutscene.o $(CXXFLAGS)

Sound.o: Sound.cpp
	$(CPP) -c Sound.cpp -o Sound.o $(CXXFLAGS)

Jumpscare.o: Jumpscare.cpp
	$(CPP) -c Jumpscare.cpp -o Jumpscare.o $(CXXFLAGS)

Shadow.o: Shadow.cpp
	$(CPP) -c Shadow.cpp -o Shadow.o $(CXXFLAGS)
